# Rtest_auth0
Testting auth0 in R shiny app.

It previously had a bug - 'runs locally but when deployed to shinyapps.io it doesn't work and shows the "Callback URL mismatch."'

The current version works OK.
